// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15.01.2025 10:06:25
const configMerger = require("/Users/emresahurtekin/Desktop/kepcesite/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/emresahurtekin/Desktop/kepcesite/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emresahurtekin/Desktop/kepcesite/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emresahurtekin/Desktop/kepcesite/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emresahurtekin/Desktop/kepcesite/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emresahurtekin/Desktop/kepcesite/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emresahurtekin/Desktop/kepcesite/plugins/**/*.{js,ts,mjs}","/Users/emresahurtekin/Desktop/kepcesite/composables/**/*.{js,ts,mjs}","/Users/emresahurtekin/Desktop/kepcesite/utils/**/*.{js,ts,mjs}","/Users/emresahurtekin/Desktop/kepcesite/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/emresahurtekin/Desktop/kepcesite/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/emresahurtekin/Desktop/kepcesite/app.config.{js,ts,mjs}"] } }));

module.exports = config
